# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Mr. Glow Express Car Wash
description: SpinLite Express Car Wash in Lake Worth, Florida
meta_description: "SpinLite Express Car Wash in Lake Worth, Florida"
logo: 'assets/images/mr-glow.svg'
favicon: 'favicon.ico'
email: info@mrglowcarwash.com
description: >- # this means to ignore newlines until "baseurl:"
  We are an express car wash that utilizes state of the art SpinLite® equipment dedicated to bringing you the best car wash experience imaginable. Located in Lake Worth, Florida.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mrglowcarwash.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
   - jekyll-sitemap
   - jekyll-email-protect
   - jekyll-redirect-from
   - jekyll-coffeescript
   - jekyll-webp
whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-coffeescript
  - jekyll-webp
sass:
  style: compressed
  sass_dir: _sass

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will not be checked
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/images"]

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []
############################################################

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
